sudo: required
dist: trusty

language: c

branches:
  only:
    - dev

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    packages:
      - gcc-7
      - g++-7
      - cmake
      - valgrind
      - lcov
      - cppcheck
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - sudo apt-get -y install valgrind
  - pip install --user cpp-coveralls

script:
  - pip install --user cpp-coveralls
  - export CXX=/usr/bin/g++-7
  - export C=/usr/bin/gcc-7
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - valgrind --tool=memcheck --leak-check=full --leak-resolution=med ./test/runTest
  - cppcheck --enable=all --std=c11 --check-config --suppress=missingIncludeSystem -I ../include ../src
  - ctest --output-on-failure

after_success:
  - echo "SUCCESS"

