sudo: required
dist: trusty

language: c

branches:
  only:
    - dev

os:
  - linux

compiler:
  - gcc

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc

      addons:
        apt:
          packages:
            - cmake
            - gcc
            - g++
            - valgrind
            - lcov
            - cppcheck
          sources:
            - ubuntu-toolchain-r-test

before_install:
  - sudo apt-get -y install valgrind
  - pip install --user cpp-coveralls

script:
  - pip install --user cpp-coveralls
  - export CXX=/usr/bin/g++-7
  - export C=/usr/bin/gcc-7
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - valgrind --tool=memcheck --leak-check=full --leak-resolution=med ./test/matrix_test
  - cppcheck --enable=all --std=c11 --check-config --suppress=missingIncludeSystem -I ../include ../src
  - ctest --output-on-failure

after_success:
  - echo "SUCCESS"

