sudo: required
dist: trusty

language: c

branches:
  only:
    - dev

os:
  - linux

compiler:
  - gcc

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc

      addons:
        apt:
          packages:
            - cmake
            - gcc-7
            - g++-7
            - valgrind
            - python-yaml
            - lcov
            - valgrind
          sources:
            - ubuntu-toolchain-r-test

before_install:
  - sudo apt-get -y install valgrind
  - pip install --user cpp-coveralls

script:
  - export CXX=/usr/bin/g++-7
  - export C=/usr/bin/gcc-7
  - mkdir build
  - cd build
  - cmake ..
  - make
#  - ctest

after_success:
  - echo "SUCCESS"

